name: haraka_afya_ai_website
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  url_launcher: ^6.3.0
  font_awesome_flutter: ^10.9.0

  cupertino_icons: ^1.0.8
  js: ^0.7.2
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

assets:
  - assets/images/logo.png
  - assets/images/ridge.jpg
  - assets/images/samuel.jpg
  - assets/images/joy.jpg
